coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.addr[0]} {hw_prefetch_arb_out_req.addr[1]} {hw_prefetch_arb_out_req.addr[2]} {hw_prefetch_arb_out_req.addr[3]} {hw_prefetch_arb_out_req.addr[4]} {hw_prefetch_arb_out_req.addr[5]} -comment "The hwpf_stride is only sending addresses aligned on 64 bits, meaning that the 6 LSB of this signal are not going to be used" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.sid[0]} {hw_prefetch_arb_out_req.sid[1]} {hw_prefetch_arb_out_req.sid[2]} -comment "The SID is fixed to 0 in the design, because it is up to the integration to fix the SID value that is send on the hwpf_stride hpdcache interface into the hpdcache, by fixing it in hard in the top module" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.size[1]} -comment "The hwpf_stride is only sending HPDCACHE_REQ_CMO_PREFETCH operation into the Dcache. The size used for this operation is 'h5, which means this bit is never used." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode hw_prefetch_arb_out_req.uncacheable -comment "This signal is overidden in the hwpf_stride_wrapper module by the cacheable signal, which is why it is never toggled" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[0][0]} {hw_prefetch_arb_out_req.wdata[0][1]} {hw_prefetch_arb_out_req.wdata[0][2]} {hw_prefetch_arb_out_req.wdata[0][3]} {hw_prefetch_arb_out_req.wdata[0][4]} {hw_prefetch_arb_out_req.wdata[0][5]} {hw_prefetch_arb_out_req.wdata[0][6]} {hw_prefetch_arb_out_req.wdata[0][7]} {hw_prefetch_arb_out_req.wdata[0][8]} {hw_prefetch_arb_out_req.wdata[0][9]} -comment "The hwpf_strides don't send any data into the hpdcache, \
only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[0][10]} {hw_prefetch_arb_out_req.wdata[0][11]} {hw_prefetch_arb_out_req.wdata[0][12]} {hw_prefetch_arb_out_req.wdata[0][13]} {hw_prefetch_arb_out_req.wdata[0][14]} {hw_prefetch_arb_out_req.wdata[0][15]} {hw_prefetch_arb_out_req.wdata[0][16]} {hw_prefetch_arb_out_req.wdata[0][17]} {hw_prefetch_arb_out_req.wdata[0][18]} {hw_prefetch_arb_out_req.wdata[0][19]} -comment "The hwpf_strides don't send any data \
into the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[0][20]} {hw_prefetch_arb_out_req.wdata[0][21]} {hw_prefetch_arb_out_req.wdata[0][22]} {hw_prefetch_arb_out_req.wdata[0][23]} {hw_prefetch_arb_out_req.wdata[0][24]} {hw_prefetch_arb_out_req.wdata[0][25]} {hw_prefetch_arb_out_req.wdata[0][26]} {hw_prefetch_arb_out_req.wdata[0][27]} {hw_prefetch_arb_out_req.wdata[0][28]} {hw_prefetch_arb_out_req.wdata[0][29]} -comment "The hwpf_strides don't send any data \
into the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[0][30]} {hw_prefetch_arb_out_req.wdata[0][31]} {hw_prefetch_arb_out_req.wdata[0][32]} {hw_prefetch_arb_out_req.wdata[0][33]} {hw_prefetch_arb_out_req.wdata[0][34]} {hw_prefetch_arb_out_req.wdata[0][35]} {hw_prefetch_arb_out_req.wdata[0][36]} {hw_prefetch_arb_out_req.wdata[0][37]} {hw_prefetch_arb_out_req.wdata[0][38]} {hw_prefetch_arb_out_req.wdata[0][39]} -comment "The hwpf_strides don't send any data \
into the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[0][40]} {hw_prefetch_arb_out_req.wdata[0][41]} {hw_prefetch_arb_out_req.wdata[0][42]} {hw_prefetch_arb_out_req.wdata[0][43]} {hw_prefetch_arb_out_req.wdata[0][44]} {hw_prefetch_arb_out_req.wdata[0][45]} {hw_prefetch_arb_out_req.wdata[0][46]} {hw_prefetch_arb_out_req.wdata[0][47]} {hw_prefetch_arb_out_req.wdata[0][48]} {hw_prefetch_arb_out_req.wdata[0][49]} -comment "The hwpf_strides don't send any data \
into the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[0][50]} {hw_prefetch_arb_out_req.wdata[0][51]} {hw_prefetch_arb_out_req.wdata[0][52]} {hw_prefetch_arb_out_req.wdata[0][53]} {hw_prefetch_arb_out_req.wdata[0][54]} {hw_prefetch_arb_out_req.wdata[0][55]} {hw_prefetch_arb_out_req.wdata[0][56]} {hw_prefetch_arb_out_req.wdata[0][57]} {hw_prefetch_arb_out_req.wdata[0][58]} {hw_prefetch_arb_out_req.wdata[0][59]} -comment "The hwpf_strides don't send any data \
into the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[0][60]} {hw_prefetch_arb_out_req.wdata[0][61]} {hw_prefetch_arb_out_req.wdata[0][62]} {hw_prefetch_arb_out_req.wdata[0][63]} {hw_prefetch_arb_out_req.wdata[1][0]} {hw_prefetch_arb_out_req.wdata[1][1]} {hw_prefetch_arb_out_req.wdata[1][2]} {hw_prefetch_arb_out_req.wdata[1][3]} {hw_prefetch_arb_out_req.wdata[1][4]} {hw_prefetch_arb_out_req.wdata[1][5]} -comment "The hwpf_strides don't send any data into the \
hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[1][6]} {hw_prefetch_arb_out_req.wdata[1][7]} {hw_prefetch_arb_out_req.wdata[1][8]} {hw_prefetch_arb_out_req.wdata[1][9]} {hw_prefetch_arb_out_req.wdata[1][10]} {hw_prefetch_arb_out_req.wdata[1][11]} {hw_prefetch_arb_out_req.wdata[1][12]} {hw_prefetch_arb_out_req.wdata[1][13]} {hw_prefetch_arb_out_req.wdata[1][14]} {hw_prefetch_arb_out_req.wdata[1][15]} -comment "The hwpf_strides don't send any data into \
the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[1][16]} {hw_prefetch_arb_out_req.wdata[1][17]} {hw_prefetch_arb_out_req.wdata[1][18]} {hw_prefetch_arb_out_req.wdata[1][19]} {hw_prefetch_arb_out_req.wdata[1][20]} {hw_prefetch_arb_out_req.wdata[1][21]} {hw_prefetch_arb_out_req.wdata[1][22]} {hw_prefetch_arb_out_req.wdata[1][23]} {hw_prefetch_arb_out_req.wdata[1][24]} {hw_prefetch_arb_out_req.wdata[1][25]} -comment "The hwpf_strides don't send any data \
into the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[1][26]} {hw_prefetch_arb_out_req.wdata[1][27]} {hw_prefetch_arb_out_req.wdata[1][28]} {hw_prefetch_arb_out_req.wdata[1][29]} {hw_prefetch_arb_out_req.wdata[1][30]} {hw_prefetch_arb_out_req.wdata[1][31]} {hw_prefetch_arb_out_req.wdata[1][32]} {hw_prefetch_arb_out_req.wdata[1][33]} {hw_prefetch_arb_out_req.wdata[1][34]} {hw_prefetch_arb_out_req.wdata[1][35]} -comment "The hwpf_strides don't send any data \
into the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[1][36]} {hw_prefetch_arb_out_req.wdata[1][37]} {hw_prefetch_arb_out_req.wdata[1][38]} {hw_prefetch_arb_out_req.wdata[1][39]} {hw_prefetch_arb_out_req.wdata[1][40]} {hw_prefetch_arb_out_req.wdata[1][41]} {hw_prefetch_arb_out_req.wdata[1][42]} {hw_prefetch_arb_out_req.wdata[1][43]} {hw_prefetch_arb_out_req.wdata[1][44]} {hw_prefetch_arb_out_req.wdata[1][45]} -comment "The hwpf_strides don't send any data \
into the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[1][46]} {hw_prefetch_arb_out_req.wdata[1][47]} {hw_prefetch_arb_out_req.wdata[1][48]} {hw_prefetch_arb_out_req.wdata[1][49]} {hw_prefetch_arb_out_req.wdata[1][50]} {hw_prefetch_arb_out_req.wdata[1][51]} {hw_prefetch_arb_out_req.wdata[1][52]} {hw_prefetch_arb_out_req.wdata[1][53]} {hw_prefetch_arb_out_req.wdata[1][54]} {hw_prefetch_arb_out_req.wdata[1][55]} -comment "The hwpf_strides don't send any data \
into the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_arb_out_req.wdata[1][56]} {hw_prefetch_arb_out_req.wdata[1][57]} {hw_prefetch_arb_out_req.wdata[1][58]} {hw_prefetch_arb_out_req.wdata[1][59]} {hw_prefetch_arb_out_req.wdata[1][60]} {hw_prefetch_arb_out_req.wdata[1][61]} {hw_prefetch_arb_out_req.wdata[1][62]} {hw_prefetch_arb_out_req.wdata[1][63]} -comment "The hwpf_strides don't send any data into the hpdcache, only HPDCACHE_REQ_CMO_PREFETCH requests which doesn't need data." \

coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_base_int[0][4]} {hw_prefetch_base_int[0][5]} {hw_prefetch_base_int[1][4]} {hw_prefetch_base_int[1][5]} {hw_prefetch_base_int[2][4]} {hw_prefetch_base_int[2][5]} {hw_prefetch_base_int[3][4]} {hw_prefetch_base_int[3][5]} {hw_prefetch_cfg_i[0].hw_prefetch_base[4]} {hw_prefetch_cfg_i[0].hw_prefetch_base[5]} -comment "These bits are reserved in the BASE register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[0].hw_prefetch_param[36]} {hw_prefetch_cfg_i[0].hw_prefetch_param[37]} {hw_prefetch_cfg_i[0].hw_prefetch_param[38]} {hw_prefetch_cfg_i[0].hw_prefetch_param[39]} {hw_prefetch_cfg_i[0].hw_prefetch_param[56]} {hw_prefetch_cfg_i[0].hw_prefetch_param[57]} {hw_prefetch_cfg_i[0].hw_prefetch_param[58]} {hw_prefetch_cfg_i[0].hw_prefetch_param[59]} {hw_prefetch_cfg_i[0].hw_prefetch_param[60]} {hw_prefetch_cfg_i[0].hw_prefetch_param[61]} \
-comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[0].hw_prefetch_param[62]} {hw_prefetch_cfg_i[0].hw_prefetch_param[63]} -comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[0].hw_prefetch_snoop[0]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[1]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[2]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[3]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[4]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[5]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[6]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[7]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[8]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[9]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[0].hw_prefetch_snoop[10]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[11]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[12]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[13]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[14]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[15]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[16]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[17]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[18]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[19]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[0].hw_prefetch_snoop[20]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[21]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[22]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[23]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[24]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[25]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[26]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[27]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[28]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[29]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[0].hw_prefetch_snoop[30]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[31]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[32]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[33]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[34]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[35]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[36]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[37]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[38]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[39]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[0].hw_prefetch_snoop[40]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[41]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[42]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[43]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[44]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[45]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[46]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[47]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[48]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[49]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[0].hw_prefetch_snoop[50]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[51]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[52]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[53]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[54]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[55]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[56]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[57]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[58]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[59]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[0].hw_prefetch_snoop[60]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[61]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[62]} {hw_prefetch_cfg_i[0].hw_prefetch_snoop[63]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[1].hw_prefetch_base[4]} {hw_prefetch_cfg_i[1].hw_prefetch_base[5]} -comment "These bits are reserved in the BASE register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[1].hw_prefetch_param[36]} {hw_prefetch_cfg_i[1].hw_prefetch_param[37]} {hw_prefetch_cfg_i[1].hw_prefetch_param[38]} {hw_prefetch_cfg_i[1].hw_prefetch_param[39]} {hw_prefetch_cfg_i[1].hw_prefetch_param[56]} {hw_prefetch_cfg_i[1].hw_prefetch_param[57]} {hw_prefetch_cfg_i[1].hw_prefetch_param[58]} {hw_prefetch_cfg_i[1].hw_prefetch_param[59]} {hw_prefetch_cfg_i[1].hw_prefetch_param[60]} {hw_prefetch_cfg_i[1].hw_prefetch_param[61]} \
-comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[1].hw_prefetch_param[62]} {hw_prefetch_cfg_i[1].hw_prefetch_param[63]} -comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[1].hw_prefetch_snoop[0]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[1]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[2]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[3]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[4]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[5]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[6]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[7]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[8]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[9]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[1].hw_prefetch_snoop[10]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[11]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[12]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[13]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[14]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[15]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[16]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[17]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[18]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[19]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[1].hw_prefetch_snoop[20]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[21]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[22]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[23]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[24]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[25]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[26]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[27]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[28]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[29]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[1].hw_prefetch_snoop[30]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[31]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[32]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[33]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[34]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[35]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[36]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[37]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[38]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[39]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[1].hw_prefetch_snoop[40]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[41]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[42]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[43]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[44]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[45]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[46]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[47]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[48]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[49]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[1].hw_prefetch_snoop[50]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[51]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[52]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[53]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[54]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[55]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[56]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[57]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[58]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[59]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[1].hw_prefetch_snoop[60]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[61]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[62]} {hw_prefetch_cfg_i[1].hw_prefetch_snoop[63]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[2].hw_prefetch_base[4]} {hw_prefetch_cfg_i[2].hw_prefetch_base[5]} -comment "These bits are reserved in the BASE register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[2].hw_prefetch_param[36]} {hw_prefetch_cfg_i[2].hw_prefetch_param[37]} {hw_prefetch_cfg_i[2].hw_prefetch_param[38]} {hw_prefetch_cfg_i[2].hw_prefetch_param[39]} {hw_prefetch_cfg_i[2].hw_prefetch_param[56]} {hw_prefetch_cfg_i[2].hw_prefetch_param[57]} {hw_prefetch_cfg_i[2].hw_prefetch_param[58]} {hw_prefetch_cfg_i[2].hw_prefetch_param[59]} {hw_prefetch_cfg_i[2].hw_prefetch_param[60]} {hw_prefetch_cfg_i[2].hw_prefetch_param[61]} \
-comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[2].hw_prefetch_param[62]} {hw_prefetch_cfg_i[2].hw_prefetch_param[63]} -comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[2].hw_prefetch_snoop[0]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[1]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[2]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[3]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[4]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[5]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[6]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[7]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[8]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[9]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[2].hw_prefetch_snoop[10]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[11]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[12]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[13]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[14]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[15]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[16]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[17]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[18]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[19]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[2].hw_prefetch_snoop[20]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[21]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[22]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[23]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[24]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[25]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[26]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[27]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[28]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[29]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[2].hw_prefetch_snoop[30]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[31]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[32]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[33]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[34]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[35]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[36]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[37]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[38]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[39]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[2].hw_prefetch_snoop[40]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[41]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[42]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[43]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[44]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[45]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[46]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[47]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[48]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[49]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[2].hw_prefetch_snoop[50]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[51]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[52]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[53]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[54]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[55]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[56]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[57]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[58]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[59]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[2].hw_prefetch_snoop[60]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[61]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[62]} {hw_prefetch_cfg_i[2].hw_prefetch_snoop[63]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[3].hw_prefetch_base[4]} {hw_prefetch_cfg_i[3].hw_prefetch_base[5]} -comment "These bits are reserved in the BASE register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[3].hw_prefetch_param[36]} {hw_prefetch_cfg_i[3].hw_prefetch_param[37]} {hw_prefetch_cfg_i[3].hw_prefetch_param[38]} {hw_prefetch_cfg_i[3].hw_prefetch_param[39]} {hw_prefetch_cfg_i[3].hw_prefetch_param[56]} {hw_prefetch_cfg_i[3].hw_prefetch_param[57]} {hw_prefetch_cfg_i[3].hw_prefetch_param[58]} {hw_prefetch_cfg_i[3].hw_prefetch_param[59]} {hw_prefetch_cfg_i[3].hw_prefetch_param[60]} {hw_prefetch_cfg_i[3].hw_prefetch_param[61]} \
-comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[3].hw_prefetch_param[62]} {hw_prefetch_cfg_i[3].hw_prefetch_param[63]} -comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[3].hw_prefetch_snoop[0]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[1]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[2]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[3]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[4]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[5]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[6]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[7]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[8]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[9]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[3].hw_prefetch_snoop[10]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[11]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[12]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[13]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[14]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[15]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[16]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[17]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[18]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[19]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[3].hw_prefetch_snoop[20]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[21]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[22]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[23]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[24]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[25]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[26]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[27]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[28]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[29]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[3].hw_prefetch_snoop[30]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[31]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[32]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[33]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[34]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[35]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[36]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[37]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[38]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[39]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[3].hw_prefetch_snoop[40]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[41]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[42]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[43]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[44]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[45]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[46]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[47]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[48]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[49]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[3].hw_prefetch_snoop[50]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[51]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[52]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[53]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[54]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[55]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[56]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[57]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[58]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[59]} \
-comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_cfg_i[3].hw_prefetch_snoop[60]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[61]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[62]} {hw_prefetch_cfg_i[3].hw_prefetch_snoop[63]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_param_int[0][36]} {hw_prefetch_param_int[0][37]} {hw_prefetch_param_int[0][38]} {hw_prefetch_param_int[0][39]} {hw_prefetch_param_int[0][56]} {hw_prefetch_param_int[0][57]} {hw_prefetch_param_int[0][58]} {hw_prefetch_param_int[0][59]} {hw_prefetch_param_int[0][60]} {hw_prefetch_param_int[0][61]} -comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_param_int[0][62]} {hw_prefetch_param_int[0][63]} {hw_prefetch_param_int[1][36]} {hw_prefetch_param_int[1][37]} {hw_prefetch_param_int[1][38]} {hw_prefetch_param_int[1][39]} {hw_prefetch_param_int[1][56]} {hw_prefetch_param_int[1][57]} {hw_prefetch_param_int[1][58]} {hw_prefetch_param_int[1][59]} -comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_param_int[1][60]} {hw_prefetch_param_int[1][61]} {hw_prefetch_param_int[1][62]} {hw_prefetch_param_int[1][63]} {hw_prefetch_param_int[2][36]} {hw_prefetch_param_int[2][37]} {hw_prefetch_param_int[2][38]} {hw_prefetch_param_int[2][39]} {hw_prefetch_param_int[2][56]} {hw_prefetch_param_int[2][57]} -comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_param_int[2][58]} {hw_prefetch_param_int[2][59]} {hw_prefetch_param_int[2][60]} {hw_prefetch_param_int[2][61]} {hw_prefetch_param_int[2][62]} {hw_prefetch_param_int[2][63]} {hw_prefetch_param_int[3][36]} {hw_prefetch_param_int[3][37]} {hw_prefetch_param_int[3][38]} {hw_prefetch_param_int[3][39]} -comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_param_int[3][56]} {hw_prefetch_param_int[3][57]} {hw_prefetch_param_int[3][58]} {hw_prefetch_param_int[3][59]} {hw_prefetch_param_int[3][60]} {hw_prefetch_param_int[3][61]} {hw_prefetch_param_int[3][62]} {hw_prefetch_param_int[3][63]} -comment "These bits are reserved in the PARAM register, and are of no use so there are never going to toggle" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[0][0]} {hw_prefetch_snoop_int[0][1]} {hw_prefetch_snoop_int[0][2]} {hw_prefetch_snoop_int[0][3]} {hw_prefetch_snoop_int[0][4]} {hw_prefetch_snoop_int[0][5]} {hw_prefetch_snoop_int[0][6]} {hw_prefetch_snoop_int[0][7]} {hw_prefetch_snoop_int[0][8]} {hw_prefetch_snoop_int[0][9]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[0][10]} {hw_prefetch_snoop_int[0][11]} {hw_prefetch_snoop_int[0][12]} {hw_prefetch_snoop_int[0][13]} {hw_prefetch_snoop_int[0][14]} {hw_prefetch_snoop_int[0][15]} {hw_prefetch_snoop_int[0][16]} {hw_prefetch_snoop_int[0][17]} {hw_prefetch_snoop_int[0][18]} {hw_prefetch_snoop_int[0][19]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[0][20]} {hw_prefetch_snoop_int[0][21]} {hw_prefetch_snoop_int[0][22]} {hw_prefetch_snoop_int[0][23]} {hw_prefetch_snoop_int[0][24]} {hw_prefetch_snoop_int[0][25]} {hw_prefetch_snoop_int[0][26]} {hw_prefetch_snoop_int[0][27]} {hw_prefetch_snoop_int[0][28]} {hw_prefetch_snoop_int[0][29]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[0][30]} {hw_prefetch_snoop_int[0][31]} {hw_prefetch_snoop_int[0][32]} {hw_prefetch_snoop_int[0][33]} {hw_prefetch_snoop_int[0][34]} {hw_prefetch_snoop_int[0][35]} {hw_prefetch_snoop_int[0][36]} {hw_prefetch_snoop_int[0][37]} {hw_prefetch_snoop_int[0][38]} {hw_prefetch_snoop_int[0][39]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[0][40]} {hw_prefetch_snoop_int[0][41]} {hw_prefetch_snoop_int[0][42]} {hw_prefetch_snoop_int[0][43]} {hw_prefetch_snoop_int[0][44]} {hw_prefetch_snoop_int[0][45]} {hw_prefetch_snoop_int[0][46]} {hw_prefetch_snoop_int[0][47]} {hw_prefetch_snoop_int[0][48]} {hw_prefetch_snoop_int[0][49]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[0][50]} {hw_prefetch_snoop_int[0][51]} {hw_prefetch_snoop_int[0][52]} {hw_prefetch_snoop_int[0][53]} {hw_prefetch_snoop_int[0][54]} {hw_prefetch_snoop_int[0][55]} {hw_prefetch_snoop_int[0][56]} {hw_prefetch_snoop_int[0][57]} {hw_prefetch_snoop_int[0][58]} {hw_prefetch_snoop_int[0][59]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[0][60]} {hw_prefetch_snoop_int[0][61]} {hw_prefetch_snoop_int[0][62]} {hw_prefetch_snoop_int[0][63]} {hw_prefetch_snoop_int[1][0]} {hw_prefetch_snoop_int[1][1]} {hw_prefetch_snoop_int[1][2]} {hw_prefetch_snoop_int[1][3]} {hw_prefetch_snoop_int[1][4]} {hw_prefetch_snoop_int[1][5]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[1][6]} {hw_prefetch_snoop_int[1][7]} {hw_prefetch_snoop_int[1][8]} {hw_prefetch_snoop_int[1][9]} {hw_prefetch_snoop_int[1][10]} {hw_prefetch_snoop_int[1][11]} {hw_prefetch_snoop_int[1][12]} {hw_prefetch_snoop_int[1][13]} {hw_prefetch_snoop_int[1][14]} {hw_prefetch_snoop_int[1][15]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[1][16]} {hw_prefetch_snoop_int[1][17]} {hw_prefetch_snoop_int[1][18]} {hw_prefetch_snoop_int[1][19]} {hw_prefetch_snoop_int[1][20]} {hw_prefetch_snoop_int[1][21]} {hw_prefetch_snoop_int[1][22]} {hw_prefetch_snoop_int[1][23]} {hw_prefetch_snoop_int[1][24]} {hw_prefetch_snoop_int[1][25]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[1][26]} {hw_prefetch_snoop_int[1][27]} {hw_prefetch_snoop_int[1][28]} {hw_prefetch_snoop_int[1][29]} {hw_prefetch_snoop_int[1][30]} {hw_prefetch_snoop_int[1][31]} {hw_prefetch_snoop_int[1][32]} {hw_prefetch_snoop_int[1][33]} {hw_prefetch_snoop_int[1][34]} {hw_prefetch_snoop_int[1][35]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[1][36]} {hw_prefetch_snoop_int[1][37]} {hw_prefetch_snoop_int[1][38]} {hw_prefetch_snoop_int[1][39]} {hw_prefetch_snoop_int[1][40]} {hw_prefetch_snoop_int[1][41]} {hw_prefetch_snoop_int[1][42]} {hw_prefetch_snoop_int[1][43]} {hw_prefetch_snoop_int[1][44]} {hw_prefetch_snoop_int[1][45]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[1][46]} {hw_prefetch_snoop_int[1][47]} {hw_prefetch_snoop_int[1][48]} {hw_prefetch_snoop_int[1][49]} {hw_prefetch_snoop_int[1][50]} {hw_prefetch_snoop_int[1][51]} {hw_prefetch_snoop_int[1][52]} {hw_prefetch_snoop_int[1][53]} {hw_prefetch_snoop_int[1][54]} {hw_prefetch_snoop_int[1][55]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[1][56]} {hw_prefetch_snoop_int[1][57]} {hw_prefetch_snoop_int[1][58]} {hw_prefetch_snoop_int[1][59]} {hw_prefetch_snoop_int[1][60]} {hw_prefetch_snoop_int[1][61]} {hw_prefetch_snoop_int[1][62]} {hw_prefetch_snoop_int[1][63]} {hw_prefetch_snoop_int[2][0]} {hw_prefetch_snoop_int[2][1]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[2][2]} {hw_prefetch_snoop_int[2][3]} {hw_prefetch_snoop_int[2][4]} {hw_prefetch_snoop_int[2][5]} {hw_prefetch_snoop_int[2][6]} {hw_prefetch_snoop_int[2][7]} {hw_prefetch_snoop_int[2][8]} {hw_prefetch_snoop_int[2][9]} {hw_prefetch_snoop_int[2][10]} {hw_prefetch_snoop_int[2][11]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[2][12]} {hw_prefetch_snoop_int[2][13]} {hw_prefetch_snoop_int[2][14]} {hw_prefetch_snoop_int[2][15]} {hw_prefetch_snoop_int[2][16]} {hw_prefetch_snoop_int[2][17]} {hw_prefetch_snoop_int[2][18]} {hw_prefetch_snoop_int[2][19]} {hw_prefetch_snoop_int[2][20]} {hw_prefetch_snoop_int[2][21]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[2][22]} {hw_prefetch_snoop_int[2][23]} {hw_prefetch_snoop_int[2][24]} {hw_prefetch_snoop_int[2][25]} {hw_prefetch_snoop_int[2][26]} {hw_prefetch_snoop_int[2][27]} {hw_prefetch_snoop_int[2][28]} {hw_prefetch_snoop_int[2][29]} {hw_prefetch_snoop_int[2][30]} {hw_prefetch_snoop_int[2][31]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[2][32]} {hw_prefetch_snoop_int[2][33]} {hw_prefetch_snoop_int[2][34]} {hw_prefetch_snoop_int[2][35]} {hw_prefetch_snoop_int[2][36]} {hw_prefetch_snoop_int[2][37]} {hw_prefetch_snoop_int[2][38]} {hw_prefetch_snoop_int[2][39]} {hw_prefetch_snoop_int[2][40]} {hw_prefetch_snoop_int[2][41]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[2][42]} {hw_prefetch_snoop_int[2][43]} {hw_prefetch_snoop_int[2][44]} {hw_prefetch_snoop_int[2][45]} {hw_prefetch_snoop_int[2][46]} {hw_prefetch_snoop_int[2][47]} {hw_prefetch_snoop_int[2][48]} {hw_prefetch_snoop_int[2][49]} {hw_prefetch_snoop_int[2][50]} {hw_prefetch_snoop_int[2][51]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[2][52]} {hw_prefetch_snoop_int[2][53]} {hw_prefetch_snoop_int[2][54]} {hw_prefetch_snoop_int[2][55]} {hw_prefetch_snoop_int[2][56]} {hw_prefetch_snoop_int[2][57]} {hw_prefetch_snoop_int[2][58]} {hw_prefetch_snoop_int[2][59]} {hw_prefetch_snoop_int[2][60]} {hw_prefetch_snoop_int[2][61]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[2][62]} {hw_prefetch_snoop_int[2][63]} {hw_prefetch_snoop_int[3][0]} {hw_prefetch_snoop_int[3][1]} {hw_prefetch_snoop_int[3][2]} {hw_prefetch_snoop_int[3][3]} {hw_prefetch_snoop_int[3][4]} {hw_prefetch_snoop_int[3][5]} {hw_prefetch_snoop_int[3][6]} {hw_prefetch_snoop_int[3][7]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[3][8]} {hw_prefetch_snoop_int[3][9]} {hw_prefetch_snoop_int[3][10]} {hw_prefetch_snoop_int[3][11]} {hw_prefetch_snoop_int[3][12]} {hw_prefetch_snoop_int[3][13]} {hw_prefetch_snoop_int[3][14]} {hw_prefetch_snoop_int[3][15]} {hw_prefetch_snoop_int[3][16]} {hw_prefetch_snoop_int[3][17]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[3][18]} {hw_prefetch_snoop_int[3][19]} {hw_prefetch_snoop_int[3][20]} {hw_prefetch_snoop_int[3][21]} {hw_prefetch_snoop_int[3][22]} {hw_prefetch_snoop_int[3][23]} {hw_prefetch_snoop_int[3][24]} {hw_prefetch_snoop_int[3][25]} {hw_prefetch_snoop_int[3][26]} {hw_prefetch_snoop_int[3][27]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[3][28]} {hw_prefetch_snoop_int[3][29]} {hw_prefetch_snoop_int[3][30]} {hw_prefetch_snoop_int[3][31]} {hw_prefetch_snoop_int[3][32]} {hw_prefetch_snoop_int[3][33]} {hw_prefetch_snoop_int[3][34]} {hw_prefetch_snoop_int[3][35]} {hw_prefetch_snoop_int[3][36]} {hw_prefetch_snoop_int[3][37]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[3][38]} {hw_prefetch_snoop_int[3][39]} {hw_prefetch_snoop_int[3][40]} {hw_prefetch_snoop_int[3][41]} {hw_prefetch_snoop_int[3][42]} {hw_prefetch_snoop_int[3][43]} {hw_prefetch_snoop_int[3][44]} {hw_prefetch_snoop_int[3][45]} {hw_prefetch_snoop_int[3][46]} {hw_prefetch_snoop_int[3][47]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[3][48]} {hw_prefetch_snoop_int[3][49]} {hw_prefetch_snoop_int[3][50]} {hw_prefetch_snoop_int[3][51]} {hw_prefetch_snoop_int[3][52]} {hw_prefetch_snoop_int[3][53]} {hw_prefetch_snoop_int[3][54]} {hw_prefetch_snoop_int[3][55]} {hw_prefetch_snoop_int[3][56]} {hw_prefetch_snoop_int[3][57]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_snoop_int[3][58]} {hw_prefetch_snoop_int[3][59]} {hw_prefetch_snoop_int[3][60]} {hw_prefetch_snoop_int[3][61]} {hw_prefetch_snoop_int[3][62]} {hw_prefetch_snoop_int[3][63]} -comment "This signal is never used in the design, and it is wanted by the designer" 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_status_o[4]} {hw_prefetch_status_o[5]} {hw_prefetch_status_o[6]} {hw_prefetch_status_o[7]} {hw_prefetch_status_o[8]} {hw_prefetch_status_o[9]} {hw_prefetch_status_o[10]} {hw_prefetch_status_o[11]} {hw_prefetch_status_o[12]} {hw_prefetch_status_o[13]} -comment "These bits are RESERVED in the specification of the corresponding register, and are of no uses. This is why we are ignoring them for the coverage." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_status_o[14]} {hw_prefetch_status_o[15]} {hw_prefetch_status_o[20]} {hw_prefetch_status_o[21]} {hw_prefetch_status_o[22]} {hw_prefetch_status_o[23]} {hw_prefetch_status_o[24]} {hw_prefetch_status_o[25]} {hw_prefetch_status_o[26]} {hw_prefetch_status_o[27]} -comment "These bits are RESERVED in the specification of the corresponding register, and are of no uses. This is why we are ignoring them for the coverage." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_status_o[28]} {hw_prefetch_status_o[29]} {hw_prefetch_status_o[30]} {hw_prefetch_status_o[32]} {hw_prefetch_status_o[33]} {hw_prefetch_status_o[34]} {hw_prefetch_status_o[35]} {hw_prefetch_status_o[36]} {hw_prefetch_status_o[37]} {hw_prefetch_status_o[38]} -comment "These bits are RESERVED in the specification of the corresponding register, and are of no uses. This is why we are ignoring them for the coverage." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_status_o[39]} {hw_prefetch_status_o[40]} {hw_prefetch_status_o[41]} {hw_prefetch_status_o[42]} {hw_prefetch_status_o[43]} {hw_prefetch_status_o[44]} {hw_prefetch_status_o[45]} {hw_prefetch_status_o[46]} {hw_prefetch_status_o[47]} {hw_prefetch_status_o[48]} -comment "These bits are RESERVED in the specification of the corresponding register, and are of no uses. This is why we are ignoring them for the coverage." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_status_o[49]} {hw_prefetch_status_o[50]} {hw_prefetch_status_o[51]} {hw_prefetch_status_o[52]} {hw_prefetch_status_o[53]} {hw_prefetch_status_o[54]} {hw_prefetch_status_o[55]} {hw_prefetch_status_o[56]} {hw_prefetch_status_o[57]} {hw_prefetch_status_o[58]} -comment "These bits are RESERVED in the specification of the corresponding register, and are of no uses. This is why we are ignoring them for the coverage." 
coverage exclude -scope /top/hwpf_stride_wrapper_i -togglenode {hw_prefetch_status_o[59]} {hw_prefetch_status_o[60]} {hw_prefetch_status_o[61]} {hw_prefetch_status_o[62]} {hw_prefetch_status_o[63]} -comment "These bits are RESERVED in the specification of the corresponding register, and are of no uses. This is why we are ignoring them for the coverage." 
