${PROJECT_DIR}/testbench/common/hpdcache_common_pkg.sv
${PROJECT_DIR}/testbench/conf_and_perf_agent/conf_and_perf_if.sv
${PROJECT_DIR}/testbench/conf_and_perf_agent/conf_and_perf_pkg.sv
${PROJECT_DIR}/testbench/dram_mon/dram_mon_agent_pkg.sv
${PROJECT_DIR}/testbench/dram_mon/dram_if.sv
${PROJECT_DIR}/testbench/hpdcache_agent/hpdcache_agent_pkg.sv
${PROJECT_DIR}/testbench/hpdcache_agent/hpdcache_if.sv
${PROJECT_DIR}/testbench/env/hpdcache_env_pkg.sv
${PROJECT_DIR}/testbench/test/hpdcache_test_pkg.sv
${PROJECT_DIR}/testbench/top/misc_if.sv
${PROJECT_DIR}/testbench/top/hpdcache_plru_sva.sv
${PROJECT_DIR}/testbench/top/hpdcache_rrarb_sva.sv
${PROJECT_DIR}/testbench/top/hpdcache_fxarb_sva.sv
${PROJECT_DIR}/testbench/top/hpdcache_sva.sv
${PROJECT_DIR}/testbench/top/hwpf_stride_cfg_if.sv
